### ISSUE TITLE
Create new GET /user/me endpoint

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#417]
### Overview
We want to at some point be using Rest properly. Currently, this is not the case. Each endpoint which deviates from REST patterns should be duplicated and corrected. We can later migrate the frontend over to the correct endpoint and delete the incorrect usage. We don't need to be super strict but just better than where we are now. 

### Action Items

- [ ] See bloom-backend/src/user/user.controller.ts. Look for the /v1/user/me endpoint 
- [ ] Duplicate the endpoint but as a GET request. Do not delete the old version. The functionality should be the same. 
- [ ] Write some comments to explain the transition and which endpoint should be used and which is going to be archived

**Comment by mayank-sahai** [comment]
@eleanorreem looks like a quick win. I Would like to work on it. 

Just a small question. what would you prefer ?

1. New get Method function with name -> `getUserProfileByFirebaseId`  
or
2.  New get Method function with `getUserByFirebaseId`  and rename the post method to `getUserProfileByFirebaseId` (it will be discarded in future anyway)

I know this question is silly but just asking so that I don't ruin the naming convention if there is any.

**Comment by kyleecodes** [comment]
@mayank-sahai I've assigned you this issue.
And that's a really good question.
I would go with option 2, just make sure it passes all tests.
If it causes tests failures or any unexpected behavior I would use option 1 instead.
Either option ultimately works, thank you for asking!
