### ISSUE TITLE
Create user shouldn't fail when Crisp API request fails

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-backend#448]
### Overview
Currently when a user account is created, we add a crisp profile for the user. If this request to crisp fails, we propagate the error back to the user and it looks like the account creation failed. Instead of propagating the error back, we want to just highlight the error in Rollbar and send the users back a 200. 

### Action Items

- [ ] The best way to get this to work in action is to run [bloom-frontend](https://github.com/chaynHQ/bloom-frontend). In the backend, remove the CRISP api token from your backend env variables. If you try and create the user through the UI, you should be propagated back an error. 
- [ ] Look at `/bloom-backend/src/user/user.service.ts`. The `createUser` method is used to create users. You can see that a Crisp API request failure would cause the endpoint to error. 
- [ ] Update the `createUser` method so that once the user is successfully created without error, we then create a Crisp Profile. If the crisp profile fails, we get a Rollbar error and the createUser method returns successfully with the formatted user object. The Crisp API request should not throw when it fails.
- [ ] Create a service test that covers CRISP api failure in the createUser method.

**Comment by haydnba** [comment]
@eleanorreem @kyleecodes id be happy to work on this since I know the context - I'd need to get hold of some crisp tokens but I believe I can maybe just create my own account for this?

**Comment by haydnba** [comment]
looks like this may no longer be an issue as of https://github.com/chaynHQ/bloom-backend/pull/428

**Comment by eleanorreem** [comment]
Just had a look at the code and in the recent refactor, a throw was added by mistake in the method createUserServiceProfiles. So this ticket is still relevant just ever so slightly different. Feel free to pick up! I think just turning the throw into a log and writing a service test or two will safeguard the functionality in the future.

**Comment by annarhughes** [comment]
Hey @haydnba !

**The bug is indeed the `throw error` on line 81 of `serviceUserProfiles.tsx`! This was added by mistake in #428** 

Documenting some tests that could help catch this issue in future, but these can be split up and into different tasks if not all are completed now 👍 

New test in `user.service.spec.ts`
```
 it('should create user access even if crisp or mailchimp profile api fails', async () => {
      // Mocks that the accesscode already exists
      jest.spyOn(repo, 'findOne').mockResolvedValueOnce(mockPartnerAccessEntity);

      jest.spyOn(crispApi, 'createCrispProfile').mockImplementationOnce(async () => {
        throw new Error('Test throw');
      });

      jest.spyOn(mailchimpApi, 'createMailchimpProfile').mockImplementationOnce(async () => {
        throw new Error('Test throw');
      });
      // ...continue testing user as in similar create user tests
    });
```

Improve existing `partner-access.service.spec.ts` test `should assign partner access even if crisp profile api fails`, to include mailchimp, as in the user example above, making it `should create user access even if crisp or mailchimp profile api fails`

New tests on `serviceUserProfiles.tsx` to test that the following functions do not **return** an error even when an error is **thrown** - errors should be caught and not cause parent functions to fail:
- createServiceUserProfiles
- updateServiceUserProfilesUser
- updateServiceUserProfilesPartnerAccess
- updateServiceUserProfilesTherapy
- updateServiceUserProfilesCourse

**Comment by haydnba** [comment]
Ok thanks @eleanorreem and @annarhughes for the detail 🙏🏼 I'll pick this one up asap

**Comment by haydnba** [comment]
Hi @annarhughes - ok understood sorry I was not able to get on to it sooner - I'll keep the ticket assigned to me and work on the tests 👍🏼

**Comment by haydnba** [comment]
@annarhughes - PR is open here https://github.com/chaynHQ/bloom-backend/pull/478 - i hope I have understood you and implemented your suggestions correctly
